update schema. prisma with all models
MATE85-UFBA/IC045-marketplace-ufba pull request #45
Opened 2024-10-31 21:42 UTC by zxmatheus

## Problema
> _Schema do Prisma ainda tinha vários modelos faltando e alguns da definição anterior_   

> Exemplos: 
> - Todos os modelos de pesquisadores não estavam no Schema.
> - Modelo TbTags que não está diagrama mais recente estava no Schema.

## Esse PR faz:
> _Coloca todas as tabelas certas da definição do banco de dados no Schema do Prisma_

2024-11-01 00:49 UTC, mattd-silva22 commented
@zxmatheus você poderia depois focar em atualizar as seeds relacionadas ?

2024-11-01 00:51 UTC, mattd-silva22 approved these changes
Me parece tudo certo, vamos ter que focar agora em gerar pelos uma seed para cada modelo e atualizar os antigos.

2024-11-01 17:56 UTC, joel021 requested changes
Muito bom! Analisa os comentários e avançamos!

2024-11-01 17:56 UTC, joel021 commented on apps/api/prisma/schema.prisma
>  model TbUsers {
Acho que "Tb" no início e "s" no final são desnecessários na definição de um modelo de alto nível. Aqui tem alguns exemplos que acho que podemos seguir: https://www.prisma.io/docs/orm/prisma-schema/overview

2024-11-01 17:56 UTC, joel021 commented on apps/api/prisma/schema.prisma
> +  companies   TbCompanies[]
Isso é da relação "é um" de User com Company? Se sim, aqui está definido que User tem uma lista de Companies, acho que deveria ser 

company Company

Sem os colchetes, indicando que não é uma coleção

2024-11-01 17:56 UTC, joel021 commented on apps/api/prisma/schema.prisma
> +  researchers TbResearchers[]
Acho que a relação de User com Researcher também é de um para um

2024-11-01 17:56 UTC, joel021 commented on apps/api/prisma/schema.prisma
> +  created_at  DateTime        @default(now())
Vamos padronizar os nomes, como começou usando camelcase, vamos continuar assim.
Nesse caso, de "created_at" ficaria "createdAt"

2024-11-07 19:49 UTC, mattd-silva22 approved these changes

2024-11-07 19:49 UTC, mattd-silva22 commented on apps/api/prisma/schema.prisma
> +  created_at  DateTime        @default(now())
Faltou somente o update_at na tabela de users

2024-11-07 19:49 UTC, mattd-silva22 commented
Está bom o suficiente, precisamos avançar com o schemas.

Qualquer ajuste fazemos depois

2024-11-08 11:46 UTC, joel021 approved these changes

2024-11-08 11:47 UTC, merged