Add docker-compose.yml
MATE85-UFBA/IC045-marketplace-ufba pull request #46
Opened 2024-10-31 23:07 UTC by 1pedro

## Problema
Precisamos substituir o Dockerfile por um docker-compose visto que fica mais facil o gerenciamento do container.

## Esse PR faz:
 - [ ] Remove diretório `apps/api/infra`
 - [ ] Adiciona arquivo `apps/api/docker-compose.yml`

2024-10-31 23:54 UTC, joel021 approved these changes

2024-11-01 00:53 UTC, mattd-silva22 requested changes
@1pedro , poderiam atualizar o playbook com as instruções de como utilizar o compose?

2024-11-06 01:05 UTC, mattd-silva22 commented
@1pedro conseguiu atualizar o Playbook?

2024-11-08 22:00 UTC, felipejrvieira commented
@mattd-silva22 acabei de fazer o merge que adiciona docker-compose ao projeto. Acabei não adicionando volume e ao invés de editar o playbook, coloquei as instruções no próprio commit https://github.com/MATE85-UFBA/IC045-marketplace-ufba/commit/791e68c3ce609dd5bac9f3c415b7fcd5751491f6
Depois veja se as instruções estão claras. Se tiver, faço um novo PR.

2024-11-12 22:24 UTC, closed without merging